module.exports = {
  category: [
    { text: "便利ツール", slug: "tool" },
    { text: "節約", slug: "saving" },
    { text: "コラム", slug: "column" },
    { text: "買い物レポート", slug: "report" },
  ],
  tags: [
    { text: "モバイルアプリ", slug: "mobile-app" },
    { text: "Webアプリ", slug: "web-app" },
    { text: "自作アプリ", slug: "self-made-app" },
    { text: "買い物リスト", slug: "kaimono-list" },
    { text: "便利", slug: "convenience" },
    { text: "レシピ", slug: "recipe" },
    { text: "献立", slug: "menu" },
    { text: "安い", slug: "cheap" },
    { text: "美味しい", slug: "delicious" },
    { text: "コスパ", slug: "cospa" },
    { text: "食材", slug: "foodstuff" },
    { text: "海鮮", slug: "seafood" },
    { text: "食品", slug: "food" },
    { text: "非常食", slug: "emergency-food" },
    { text: "賞味期限", slug: "freshness-date" },
    { text: "防災", slug: "disaster-prevention" },
    { text: "スーパーマーケット", slug: "supermarket" },
    { text: "支払い", slug: "payment" },
    { text: "ポイント", slug: "pont" },
    { text: "クレジットカード", slug: "credit-card" },
    { text: "電子マネー", slug: "e-money" },
    { text: "QRコード決済", slug: "qr-code-clearing" },
    { text: "ヤオコー", slug: "yaoko" },
    { text: "一人暮らし", slug: "living-alone" },
    { text: "角上魚類", slug: "kakujoe" },
    { text: "日用品", slug: "commodity" },
    { text: "学生", slug: "student" },
    { text: "引越し", slug: "home-moving" },
    { text: "お惣菜", slug: "souzai" },
    { text: "ふるさと納税", slug: "hurusato-nouzei" },
    { text: "欲しいものリスト", slug: "hosimono-list" },
    { text: "コストコ", slug: "costco" },
    { text: "ダイエット", slug: "diet" },
    { text: "筋トレ", slug: "muscle-training" },
    { text: "ロピア", slug: "lopia" },
    { text: "チラシ", slug: "flyer" },
    { text: "買い物アプリ", slug: "shopping_app" },
  ],
  apps: [
    {
      name: "買い物メモ",
      slug: "kaimonomemo",
      description:
        "買い物の際に買う商品をメモしておけるアプリです。商品をカテゴリー分けしたり、メモ内容を他の人にシェアしたりすることができます。",
      img_pc: "kaimonomemo_app_pc.jpg",
      img_sp: "kaimonomemo_app_sp.png",
    },
  ],
};
